### ISSUE TITLE
Buat menjadi repository wiki

### ISSUE THREAD

**Issue by Apis035** [bert093/FFmpeg#1]
Halo,

Sekedar info; kalo mau buat repo ini jadi semacam repo wiki, isi teksnya bisa disimpan di file markdown biar dirender sama GitHub. Bisa juga tambah file README.md sebagai "daftar isi".

Misalkan isi di file README.md:
```md
# Cara menggunakan FFmpeg

- [Gambar ke video](ImageToVideo.md)
- [Video ke gambar](VideoToImage.md)
- [Encode semua format audio ke format yang berbeda](Cara convert...)
```

File yang di-link di README.md kalau di klik ntar pindah ke file itu.

Untuk format cara ngetik file markdown bisa diliat di [wiki GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#links).

Sekian

**Comment by bert093** [comment]
![Screenshot 2024-07-08 192048](https://github.com/bert093/FFmpeg/assets/103609643/988809c7-0b4b-4214-8085-c1613489f1cd)
seperti ini bg?

**Comment by bert093** [comment]
terimakasih sudah memberikan sarannya @Apis035
